"""add_diagnosis_model

Revision ID: 50a8f551100d
Revises: e676a19d7825
Create Date: 2026-08-29 04:42:34.952882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a8f551100d'
down_revision: Union[str, Sequence[str], None] = 'e676a19d7825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('reproduction_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('failure_mechanism', sa.Text(), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('affected_functions', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('alternative_causes', sa.JSON(), nullable=True),
    sa.Column('code_context', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], ),
    sa.ForeignKeyConstraint(['reproduction_id'], ['reproduction_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
