"""Add_Publication_model

Revision ID: 5571eacf3899
Revises: 8a423e24c46b
Create Date: 2026-08-30 11:42:28.981420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5571eacf3899'
down_revision: Union[str, Sequence[str], None] = '8a423e24c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repair_id', sa.String(), nullable=False),
    sa.Column('repository_owner', sa.String(), nullable=True),
    sa.Column('repository_name', sa.String(), nullable=True),
    sa.Column('baseline_sha', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('pull_request_number', sa.Integer(), nullable=True),
    sa.Column('pull_request_url', sa.String(), nullable=True),
    sa.Column('pull_request_state', sa.String(), nullable=True),
    sa.Column('verified_patch_hash', sa.String(), nullable=True),
    sa.Column('published_patch_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    # ### end Alembic commands ###
