"""Initial

Revision ID: 5b2b513f7467
Revises: 
Create Date: 2026-08-27 11:01:19.992900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2b513f7467'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_url', sa.String(), nullable=False),
    sa.Column('repository_name', sa.String(), nullable=True),
    sa.Column('bug_description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('test_framework', sa.String(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('estimated_loc', sa.Integer(), nullable=True),
    sa.Column('has_readme', sa.Boolean(), nullable=True),
    sa.Column('important_directories', sa.JSON(), nullable=True),
    sa.Column('relevant_files', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_analyses')
    # ### end Alembic commands ###
