"""Add test_file_count

Revision ID: 623ceb385d60
Revises: 5b2b513f7467
Create Date: 2026-08-27 11:25:24.853588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623ceb385d60'
down_revision: Union[str, Sequence[str], None] = '5b2b513f7467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_analyses', sa.Column('test_file_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_analyses', 'test_file_count')
    # ### end Alembic commands ###
