"""Add_Week_5_models

Revision ID: 8a423e24c46b
Revises: fbe7b81cfbcf
Create Date: 2026-08-30 11:31:26.539392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a423e24c46b'
down_revision: Union[str, Sequence[str], None] = 'fbe7b81cfbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
