"""Add QA models

Revision ID: e676a19d7825
Revises: 623ceb385d60
Create Date: 2026-08-27 11:39:51.815364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e676a19d7825'
down_revision: Union[str, Sequence[str], None] = '623ceb385d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reproduction_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('bug_description', sa.Text(), nullable=False),
    sa.Column('test_framework', sa.String(), nullable=True),
    sa.Column('test_code', sa.Text(), nullable=True),
    sa.Column('target_files', sa.JSON(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('tests_total', sa.Integer(), nullable=True),
    sa.Column('tests_passed', sa.Integer(), nullable=True),
    sa.Column('tests_failed', sa.Integer(), nullable=True),
    sa.Column('tests_skipped', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_runs')
    op.drop_table('reproduction_attempts')
    # ### end Alembic commands ###
