"""week_5_models

Revision ID: fbe7b81cfbcf
Revises: 0f7c2e1c887d
Create Date: 2026-08-30 11:22:25.926737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe7b81cfbcf'
down_revision: Union[str, Sequence[str], None] = '0f7c2e1c887d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repair_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('patch', sa.JSON(), nullable=True),
    sa.Column('patch_metadata', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('reproduction_result', sa.JSON(), nullable=True),
    sa.Column('regression_result', sa.JSON(), nullable=True),
    sa.Column('review', sa.JSON(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('repairs', sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('repairs', sa.Column('current_attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repairs', sa.Column('final_status', sa.String(), nullable=True))
    op.add_column('repairs', sa.Column('verification_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repairs', 'verification_status')
    op.drop_column('repairs', 'final_status')
    op.drop_column('repairs', 'current_attempt')
    op.drop_column('repairs', 'max_attempts')
    op.drop_table('repair_attempts')
    # ### end Alembic commands ###
